basePath: /
definitions:
  healthcheck.HealthCheck:
    properties:
      status:
        type: string
    type: object
host: 0.0.0.0:3000
info:
  contact: {}
  license: {}
  title: API
  version: "1.0"
paths:
  /_health:
    get:
      consumes:
      - application/json
      description: application health check
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/healthcheck.HealthCheck'
      summary: Healthcheck
swagger: "2.0"
