// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/remoteday/rd-api-go/internal/config"
	"github.com/remoteday/rd-api-go/internal/db"
	"github.com/remoteday/rd-api-go/internal/platform"
	"github.com/remoteday/rd-api-go/internal/room"
	"github.com/remoteday/rd-api-go/internal/team"
)

import (
	_ "github.com/jackc/pgx/v4/stdlib"
)

// Injectors from wire.go:

func InitializeApp(config2 config.AppConfig) (platform.App, error) {
	sqlxDB, err := db.NewDatabaseConnection(config2)
	if err != nil {
		return platform.App{}, err
	}
	repository := team.NewTeamRepository(sqlxDB)
	useCase := team.NewTeamUseCase(repository)
	roomRepository := room.NewRoomRepository(sqlxDB)
	roomUseCase := room.NewRoomUseCase(roomRepository)
	app := platform.NewApp(sqlxDB, repository, useCase, roomRepository, roomUseCase)
	return app, nil
}
